[package]
name = "dithering"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
image = { version = "0.25", default-features = false, features = ["png"] }
itertools = "0.14"

[build-dependencies]
serde_yaml = "0.9"

[features]
default = ["theme"]
theme = []
